/*
 * Copyright 2024-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.agentscope.extensions.a2ui;

import io.agentscope.core.agent.RuntimeContext;
import io.agentscope.core.model.Model;
import io.agentscope.extensions.a2ui.catalog.A2uiCatalog;
import io.agentscope.extensions.a2ui.envelope.A2uiConstants;
import io.agentscope.extensions.a2ui.envelope.A2uiEnvelope;
import io.agentscope.extensions.a2ui.envelope.A2uiEnvelopeUtils;
import io.agentscope.extensions.a2ui.envelope.A2uiEnvelopeValidator;
import io.agentscope.extensions.a2ui.envelope.A2uiValidationException;
import io.agentscope.extensions.a2ui.state.A2uiSurfaceRegistry;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;
import reactor.core.publisher.Mono;

/**
 * Shared render pipeline for {@code a2ui_render} and {@code ask_user_question}. The tree-based
 * entry point {@link #renderEnvelope} validates against the catalog, resolves the surface, and
 * serializes the single-layer envelope whose JSON <em>is</em> the tool result text. {@link
 * #renderFromIntent} is the intent-based front door used by the render tool: the component tree is
 * generated by the {@link A2uiRenderManager} sub-agent call first, then goes through the same
 * envelope pipeline.
 */
public final class A2uiRenderer {

    private final A2uiConfig config;
    private final A2uiCatalog catalog;
    private final A2uiSurfaceRegistry surfaceRegistry;
    private final Supplier<Model> renderModelSupplier;
    private volatile A2uiRenderManager renderManager;

    public A2uiRenderer(
            A2uiConfig config,
            A2uiCatalog catalog,
            A2uiSurfaceRegistry surfaceRegistry,
            Supplier<Model> renderModelSupplier) {
        this.config = config;
        this.catalog = catalog;
        this.surfaceRegistry = surfaceRegistry;
        this.renderModelSupplier = renderModelSupplier;
    }

    public A2uiCatalog catalog() {
        return catalog;
    }

    /**
     * Runs the {@link A2uiRenderManager} sub-agent for the natural-language intent; the child's
     * accepted submission already went through {@link #renderEnvelope}, so the returned JSON is the
     * final envelope.
     *
     * @return Mono of the envelope JSON tool result text; fails with
     *     {@link A2uiValidationException} or {@link IllegalStateException} (no render model).
     */
    public Mono<String> renderFromIntent(
            RuntimeContext runtimeContext, String description, String context) {
        return Mono.defer(() -> renderManager().generate(runtimeContext, description, context));
    }

    private A2uiRenderManager renderManager() {
        A2uiRenderManager manager = renderManager;
        if (manager == null) {
            synchronized (this) {
                manager = renderManager;
                if (manager == null) {
                    Model model = renderModelSupplier == null ? null : renderModelSupplier.get();
                    if (model == null) {
                        throw new IllegalStateException(
                                "no render model available: pass one to the A2uiMiddleware"
                                        + " constructor or run on a model-bearing agent");
                    }
                    manager = new A2uiRenderManager(config, catalog, model, this);
                    renderManager = manager;
                }
            }
        }
        return manager;
    }

    /** @return the envelope JSON to be returned as tool result text */
    public String renderEnvelope(
            RuntimeContext runtimeContext, List<Map<String, Object>> components) {
        List<String> errors =
                A2uiEnvelopeValidator.validate(components, catalog, config.maxComponents());
        if (!errors.isEmpty()) {
            throw new A2uiValidationException(String.join(" ", errors));
        }
        A2uiSurfaceRegistry.SurfaceRef surface = surfaceRegistry.resolveOrCreate(runtimeContext);
        A2uiEnvelope envelope =
                new A2uiEnvelope(
                        A2uiConstants.PROTOCOL_VERSION,
                        surface.newlyCreated()
                                ? A2uiConstants.MESSAGE_TYPE_CREATE_SURFACE
                                : A2uiConstants.MESSAGE_TYPE_UPDATE_COMPONENTS,
                        surface.surfaceId(),
                        catalog.catalogId(),
                        components);
        return A2uiEnvelopeUtils.toJson(envelope);
    }

    @SuppressWarnings("unchecked")
    public static List<Map<String, Object>> componentsOf(Object raw) {
        if (raw instanceof List<?> list) {
            return (List<Map<String, Object>>) list;
        }
        return null;
    }
}
